### ISSUE TITLE
[documentation] Is there any place were we can find the maths ?

### ISSUE THREAD

**Issue by Wasseing** [jubishop/TuskBot#2]
I mean by that, is there any place were i can find any detailed information about the stats that are displayed by your bot ? 
For instance "aerial efficiency" i have no clue of what it means.
Thank you !

**Comment by jubishop** [comment]
hi @Wasseing !  those values come from Ballchasing.com, honestly i'm not sure what it means either LOL.  i just figured i'd report it :)
