### ISSUE TITLE
Unable to register player from ps4 with underscores

### ISSUE THREAD

**Issue by scottsmith** [jubishop/TuskBot#3]
Player has multiple underscores in their username and the issue results in being unable to retrieve stats from ballchasing as Discord appears to want to apply the underscores as markdown

Players name is Player_Name_ in both discord and on ps4

```
Now registering: PlayerName...
PlayerName successfully registered.
Now fetching ranks for: PlayerName_...
Couldn't fetch ranks for PlayerName.
```

The command to register them is: !register "Player\\\_Name\\\_" ps

It seems that the underscores aren't being escaped during the stats retrieval process as it registers just fine. When this is displayed in discord, the "Name" component in PlayerName is shown in italics.

**Comment by jubishop** [comment]
we resolved this :)
